### ISSUE TITLE
T2T Reference Genome

### ISSUE THREAD

**Issue by thomasjay3** [madagiurgiu25/decoil-pre#15]
Hi,

I was wondering if decoil currently supports  the t2t reference genome?

I used decoil on the same sample with the grch38 and then the t2t reference genome. The grch38 reference gave the expected output of a few ecDNA structures, but the t2t reference output no structures.

I followed up with another published dataset of the cell line colo320dm just to validate what I was seeing and got the same result. 

I also used bamcoverage and sniffles on those samples and the t2t and g38 reference showed that they had similar coverage and SVs.

Maybe I'm doing something incorrectly, but I was wondering if you might have any thoughts on the issue?

Thank you!

**Comment by madagiurgiu25** [comment]
Dear @thomasjay3.

Decoil does not support yet the T2T reference. It is something which will be supported soon.

However, as a quick fix, you could replace the "NC_" RefSeq annotation of the chromosomes with the corresponding "Chr1" etc then you will be able to run Decoil on your data.

**Comment by madagiurgiu25** [comment]
@thomasjay3 this was resolved in #23.

**Comment by thomasjay3** [comment]
> @thomasjay3 this was resolved in #23.

Hi @madagiurgiu25 , thanks so much for your help with this!

I gave it a try with decoil-1.1.3 and I'm seeing that the '--extend-allowed-chr' is an unrecognized argument. Is there potentially a more recent decoil version that includes this argument that I'm missing?

Thanks!
