### ISSUE TITLE
Input VCF from somatic variant callers

### ISSUE THREAD

**Issue by eesiribloom** [madagiurgiu25/decoil-pre#16]
As briefly mentioned in #14, based on my own variant calling in our cancer dataset and the respective manuscripts, long-read somatic variant callers such as nanomonsv outperform current germline callers like sniffles and cuteSV and call fewer false positives. 

I imagine many of decoil users will also be working with cancer data to detect ecDNA so it would be helpful to be able to input VCFs from such callers. 

Nanomonsv has an example VCF [here](https://github.com/friend1ws/nanomonsv/tree/master/misc/example/v0.4.0). Which is format 4.3

other potential somatic SV callers:
[SAVANA](https://github.com/cortes-ciriano-lab/savana) appears to be VCF file format 4.2
[Severus](https://github.com/KolmogorovLab/Severus) is less clear to me

**Comment by eesiribloom** [comment]
@MJoseMo It doesn't seem happy with the VCF output directly from nanomonsv. I get the same `WARNING - Corrupted VCF line` for all the variants in the VCF file and the output does not detect any ecDNA.

```
decoil reconstruct \
--bam ${BAM_INPUT} \
--vcf ${VCF_INPUT} \
--coverage ${COV_INPUT} \
--outputdir ${OUTPUT_FOLDER} \
--name ${NAME} \
--reference-genome ${GENOME} \
--annotation-gtf ${ANNO} \
--fragment-min-cov 40 \
--min-cov 40 \
--min-cov-alt 20 \
--min-vaf 0.01 \
--filter-score 40 \
--fragment-min-size 1000 \
--min-sv-len 5000

Set QUAL.MEAN_COVERAGE_WGS to  31.379556649380174
Set QUAL.MINIMAL_FRAGMENT_COVERAGE to  40
2024-09-30 16:22:39,846 - reconstruct.encode - INFO - 0. Start processing 
2024-09-30 16:22:39,846 - reconstruct.encode - INFO - nanomonsv.result.vcf
2024-09-30 16:22:39,846 - reconstruct.encode - INFO - 1. Get all breakpoints and parse SV information
2024-09-30 16:22:39,866 - reconstruct.encode - WARNING - Corrupted VCF line chr10	10389704	d_65	C	<DEL>	.	PASS	END=10389755;SVTYPE=DEL;SVLEN=-51	TR:VR	30:19	68:0
```

**Comment by MJoseMo** [comment]
Thanks @eesiribloom, I tried the software with the example data, and it completed quickly. However, have you tested it with any real sample? I ran decoil-pipeline command, and it has been running for over a day without generating any new files. How can I check the progress or what step is frozen?

**Comment by madagiurgiu25** [comment]
@MJoseMo  and @eesiribloom,

you can now run `decoil reconstruct` using the VCF files generated by `sniffles2, cutSV, and nanomonsv `. So please use the parameter `--sv-caller nanomonsv` if your input file is in `nanomonsv` format. 

If you have other questions please open another issue.

**Comment by madagiurgiu25** [comment]
> @MJoseMo It doesn't seem happy with the VCF output directly from nanomonsv. I get the same `WARNING - Corrupted VCF line` for all the variants in the VCF file and the output does not detect any ecDNA.
> 
> ```
> decoil reconstruct \
> --bam ${BAM_INPUT} \
> --vcf ${VCF_INPUT} \
> --coverage ${COV_INPUT} \
> --outputdir ${OUTPUT_FOLDER} \
> --name ${NAME} \
> --reference-genome ${GENOME} \
> --annotation-gtf ${ANNO} \
> --fragment-min-cov 40 \
> --min-cov 40 \
> --min-cov-alt 20 \
> --min-vaf 0.01 \
> --filter-score 40 \
> --fragment-min-size 1000 \
> --min-sv-len 5000
> 
> Set QUAL.MEAN_COVERAGE_WGS to  31.379556649380174
> Set QUAL.MINIMAL_FRAGMENT_COVERAGE to  40
> 2024-09-30 16:22:39,846 - reconstruct.encode - INFO - 0. Start processing 
> 2024-09-30 16:22:39,846 - reconstruct.encode - INFO - nanomonsv.result.vcf
> 2024-09-30 16:22:39,846 - reconstruct.encode - INFO - 1. Get all breakpoints and parse SV information
> 2024-09-30 16:22:39,866 - reconstruct.encode - WARNING - Corrupted VCF line chr10	10389704	d_65	C	<DEL>	.	PASS	END=10389755;SVTYPE=DEL;SVLEN=-51	TR:VR	30:19	68:0
> ```

@eesiribloom, this format does not contain the STRAND information this is why it did not work. Which means the VCF file it is not correct, and the method will not work because the SV information it is not complete.

A compatibility with `nanomonsv ` is now possible. Let me know if it worked for you using `decoil reconstruct` with `--sv-caller nanomonsv`

**Comment by eesiribloom** [comment]
I think the issue comes from this section of `encode.py`

```
def cleanvcf(vcfin, vcfout):
	"""
	Remove corrupted entries in VCF file (generated by Sniffles)
	"""
	with open(vcfout, "w") as g:
		with open(vcfin, "r") as f:
			for l in f:
				if l.startswith("#"):
					g.write(l)
				else:
					if len(l.strip().split("\t")) == 10:
						g.write(l)
					else:
						log.warning("Corrupted VCF line " + l)
```

Nanomonsv VCFs have 11 columns:
`#CHROM  POS  ID  REF  ALT  QUAL  FILTER  INFO  FORMAT  TUMOR  CONTROL`

So this seems to throw a warning with all the entries and produces an empty `clean.vcf` file

With regards to the strand information I can see that there is a separate process for nanomonsv input which transforms the vcf to contain strand info so that should't be causing the issue?

```
def transform_record_nanomonsv(record):
	# add CHR2 and POS2
	record.INFO[vp.CHR2] = record.CHROM if record.INFO[vp.SVTYPE] not in [vp.BND, vp.TRA] else record.ALT[0].mate_chrom
	record.INFO[vp.END] = record.INFO[vp.END] if record.INFO[vp.SVTYPE] not in [vp.BND, vp.TRA] else record.ALT[0].mate_pos

	# calculate AF
	record.INFO[vp.SVLEN] = '-1' if vp.SVLEN not in record.INFO or record.INFO[vp.SVLEN] == '-' else record.INFO[vp.SVLEN]
	record.INFO[vp.SVLEN] = str(record.INFO[vp.SVLEN][0]) if isinstance(record.INFO[vp.SVLEN], list) else record.INFO[vp.SVLEN]

	# SV len
	if vp.SVLEN in record.INFO:
		record.INFO[vp.SVLEN] = str(record.INFO[vp.SVLEN][0]) if isinstance(record.INFO[vp.SVLEN], list) else record.INFO[vp.SVLEN]


	# add STRANDS information
	if record.INFO[vp.SVTYPE] in [vp.BND, vp.TRA]:
		record.INFO[vp.STRAND] = record.ALT[0].orientation + record.ALT[0].mate_orientation
	elif vp.STRAND in record.INFO:
		record.INFO[vp.STRAND] = record.INFO[vp.STRAND][0]
	else:
		raise Exception("""Strand information not found {}""".format(record))
	return record
```
