### ISSUE TITLE
Problems with Decoil installacion from source. 

### ISSUE THREAD

**Issue by MJoseMo** [madagiurgiu25/decoil-pre#18]
Following the instructions in the "Install Decoil from source" section, a different  version is intalled other than 1.1.2. which is : 1.1.3-alpha. When Decoil is used through  singularity, no error occur with the example data, but when it is used 1.1.3-alpha version, an error appears during step 3. 

```
#[urlOpen] Couldn't open coverage.bw for reading
# [pyBwOpen] bw is NULL!
```

**Comment by madagiurgiu25** [comment]
Dear @MJoseMo, thank you for your request. The installation from source will install the latest version, which is not a stable one, i.e. it is still in development.

If you want to install 1.1.2 from source please download the release from github https://github.com/madagiurgiu25/decoil-pre/releases/tag/1.1.2-slim and then perform the instructions for Installing from source.

If you still want to use latest version please include the entire command and the error which you received for debugging purpose.

**Comment by madagiurgiu25** [comment]
The example is included in the docker/singularity container. 
The example is not included in the github due to size, i.e. also not available when installing from source.

**Comment by MJoseMo** [comment]
Thanks @madagiurgiu25, I have used the example of this link: https://github.com/madagiurgiu25/decoil-pre/blob/main/docs/example.md . I attached the command I used along with the corresponding error message. 
```
decoil-pipeline --version
Decoil 1.1.3-alpha
decoil-pipeline -f sv-reconstruct --bam map.bam --outputdir decoil_example_s --name example_ecDNA -r reference.fa -g anno.gtf
Found workflowfile at /ngs/conda/envs/envdecoil/lib/python3.8/site-packages/decoil-1.1.3a0-py3.8.egg/decoil/cli/sv-reconstruct.json
 decoil-pipeline --version
Decoil 1.1.3-alpha
decoil-pipeline -f sv-reconstruct --bam map.bam --outputdir decoil_example_s --name example_ecDNA -r reference.fa -g anno.gtf
Found workflowfile at /ngs/conda/envs/envdecoil/lib/python3.8/site-packages/decoil-1.1.3a0-py3.8.egg/decoil/cli/sv-reconstruct.json
--------
details!
        snakefile: /ngs/conda/envs/envdecoil/lib/python3.8/site-packages/decoil-1.1.3a0-py3.8.egg/decoil/cli/Snakefile
        workflowfile: /ngs/conda/envs/envdecoil/lib/python3.8/site-packages/decoil-1.1.3a0-py3.8.egg/decoil/cli/sv-reconstruct.json
        params: {'bam': 'map.bam', 'outputdir': 'decoil_example_s', 'reference_genome': 'reference.fa', 'annotation_gtf': 'anno.gtf', 'name': 'example_ecDNA', 'threads': 4, 'svcaller': 'sniffles', 'workflow': 'sv-reconstruct', 'container': False, 'decoil': '1.1.3-alpha'}
        target: all
--------
Building DAG of jobs...
Using shell: /bin/bash
Provided cores: 1 (use --cores to define parallelism)
Rules claiming more threads will be scaled down.
Job stats:
job          count
---------  -------
all              1
coverage         1
decoil           1
survivor         1
svcalling        1
total            5

Select jobs to execute...


rule svcalling:
    input: map.bam
    output: decoil_example_s/sv.sniffles.vcf
    log: decoil_example_s/logs/logs_sniffles
    jobid: 1
    reason: Forced execution
    wildcards: dirname=decoil_example_s
    resources: tmpdir=/junk/tmp//Etrz


            sniffles -t 4 -m map.bam             -v decoil_example_s/sv.sniffles.vcf --min_homo_af 0.7             --min_het_af 0.1 --min_length 50             --cluster --genotype --min_support 4 --report-seq &> decoil_example_s/logs/logs_sniffles

Finished job 1.
1 of 5 steps (20%) done
Select jobs to execute...


rule survivor:
    input: decoil_example_s/sv.sniffles.vcf
    output: decoil_example_s/sv.sniffles.bedpe
    log: decoil_example_s/logs/logs_survivor
    jobid: 2
    reason: Missing output files: decoil_example_s/sv.sniffles.bedpe; Input files updated by another job: decoil_example_s/sv.sniffles.vcf
    wildcards: dirname=decoil_example_s
    resources: tmpdir=/junk/tmp//Etrz


        SURVIVOR vcftobed decoil_example_s/sv.sniffles.vcf -1 -1 decoil_example_s/sv.sniffles.bedpe &> decoil_example_s/logs/logs_survivor
        

Finished job 2.
2 of 5 steps (40%) done
Select jobs to execute...


rule coverage:
    input: map.bam, map.bam.bai
    output: decoil_example_s/coverage.bw
    log: decoil_example_s/logs/logs_cov
    jobid: 3
    reason: Forced execution
    wildcards: dirname=decoil_example_s
    resources: tmpdir=/junk/tmp//Etrz


        bamCoverage --bam map.bam -o decoil_example_s/coverage.bw --binSize 50 -p 4 &> decoil_example_s/logs/logs_cov
        

Finished job 3.
3 of 5 steps (60%) done
Select jobs to execute...


rule decoil:
    input: decoil_example_s/sv.sniffles.vcf, decoil_example_s/coverage.bw, map.bam, map.bam.bai
    output: decoil_example_s/summary.txt, decoil_example_s/reconstruct.bed, decoil_example_s/reconstruct.links.txt, decoil_example_s/reconstruct.fasta, decoil_example_s/reconstruct.ecDNA.bed, decoil_example_s/reconstruct.links.ecDNA.txt, decoil_example_s/reconstruct.ecDNA.fasta, decoil_example_s/reconstruct.ecDNA.filtered.bed, decoil_example_s/reconstruct.links.ecDNA.filtered.txt, decoil_example_s/reconstruct.ecDNA.filtered.fasta
    log: decoil_example_s/logs/logs_decoil
    jobid: 4
    reason: Missing output files: decoil_example_s/reconstruct.links.txt, decoil_example_s/reconstruct.bed, decoil_example_s/reconstruct.links.ecDNA.filtered.txt, decoil_example_s/reconstruct.links.ecDNA.txt, decoil_example_s/summary.txt, decoil_example_s/reconstruct.ecDNA.bed, decoil_example_s/reconstruct.fasta, decoil_example_s/reconstruct.ecDNA.filtered.bed, decoil_example_s/reconstruct.ecDNA.filtered.fasta, decoil_example_s/reconstruct.ecDNA.fasta; Input files updated by another job: decoil_example_s/sv.sniffles.vcf, decoil_example_s/coverage.bw
    wildcards: dirname=decoil_example_s
    resources: tmpdir=/junk/tmp//Etrz

Building DAG of jobs...
Using shell: /bin/bash
Provided cores: 1 (use --cores to define parallelism)
Rules claiming more threads will be scaled down.
Select jobs to execute...
[urlOpen] Couldn't open decoil_example_s/coverage.bw for reading
[urlOpen] Couldn't open decoil_example_s/coverage.bw for reading
[pyBwOpen] bw is NULL!
[Sun Sep 29 16:55:31 2024]
Error in rule decoil:
    jobid: 0
    input: decoil_example_s/sv.sniffles.vcf, decoil_example_s/coverage.bw, map.bam, map.bam.bai
    output: decoil_example_s/summary.txt, decoil_example_s/reconstruct.bed, decoil_example_s/reconstruct.links.txt, decoil_example_s/reconstruct.fasta, decoil_example_s/reconstruct.ecDNA.bed, decoil_example_s/reconstruct.links.ecDNA.txt, decoil_example_s/reconstruct.ecDNA.fasta, decoil_example_s/reconstruct.ecDNA.filtered.bed, decoil_example_s/reconstruct.links.ecDNA.filtered.txt, decoil_example_s/reconstruct.ecDNA.filtered.fasta
    log: decoil_example_s/logs/logs_decoil (check log file(s) for error details)

RuleException:
RuntimeError in file /ngs/conda/envs/envdecoil/lib/python3.8/site-packages/decoil-1.1.3a0-py3.8.egg/decoil/cli/rules/decoil.smk, line 21:
Received an error during file opening!
  File "/ngs/conda/envs/envdecoil/lib/python3.8/site-packages/decoil-1.1.3a0-py3.8.egg/decoil/cli/rules/decoil.smk", line 21, in __rule_decoil
  File "/ngs/conda/envs/envdecoil/lib/python3.8/site-packages/decoil-1.1.3a0-py3.8.egg/decoil/main.py", line 174, in run_reconstruction
  File "/ngs/conda/envs/envdecoil/lib/python3.8/site-packages/decoil-1.1.3a0-py3.8.egg/decoil/output/metrics.py", line 106, in set_wgs
  File "/ngs/conda/envs/envdecoil/lib/python3.8/site-packages/decoil-1.1.3a0-py3.8.egg/decoil/output/metrics.py", line 80, in compute_meancov
  File "/ngs/conda/envs/envdecoil/lib/python3.8/concurrent/futures/thread.py", line 57, in run
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: .snakemake/log/2024-09-29T165353.181246.snakemake.log
-------
Status: Failed
User time (seconds): 99.22
#######

Traceback (most recent call last):
  File "/ngs/conda/envs/envdecoil/lib/python3.8/site-packages/decoil-1.1.3a0-py3.8.egg/decoil/command.py", line 170, in entry_point
    raise Exception("Snakemake failed")
Exception: Snakemake failed
```

**Comment by MJoseMo** [comment]
Dear @madagiurgiu25, I would also like to ask about the steps taken to generate the example ecdna1/map.bam file. I noticed in the header that ngmlr is used for the aligments but I am curious to know if any additional steps were done as mark duplicates or generate consensus reads ( I have seen consensus reads in IGV when loading the example file).  If so, could you indicate what programs were used for these steps ?. 

I would also like to point out that when specifying the name using the --name option, the output files are  default names (reconstruct....) instead of the specified name.

**Comment by madagiurgiu25** [comment]
> Thanks @madagiurgiu25, I have used the example of this link: https://github.com/madagiurgiu25/decoil-pre/blob/main/docs/example.md . I attached the command I used along with the corresponding error message.

This page shows how to run decoil with docker. An example is included in the docker container under the `/examples/ecdna1/map.bam` path. The example is not available when running decoil using the installation from source. 

> ```
> decoil-pipeline --version
> Decoil 1.1.3-alpha
> decoil-pipeline -f sv-reconstruct --bam map.bam --outputdir decoil_example_s --name example_ecDNA -r reference.fa -g anno.gtf
> Found workflowfile at /ngs/conda/envs/envdecoil/lib/python3.8/site-packages/decoil-1.1.3a0-py3.8.egg/decoil/cli/sv-reconstruct.json
>  decoil-pipeline --version
> Decoil 1.1.3-alpha
> decoil-pipeline -f sv-reconstruct --bam map.bam --outputdir decoil_example_s --name example_ecDNA -r reference.fa -g anno.gtf
> Found workflowfile at /ngs/conda/envs/envdecoil/lib/python3.8/site-packages/decoil-1.1.3a0-py3.8.egg/decoil/cli/sv-reconstruct.json
> --------
> details!
>         snakefile: /ngs/conda/envs/envdecoil/lib/python3.8/site-packages/decoil-1.1.3a0-py3.8.egg/decoil/cli/Snakefile
>         workflowfile: /ngs/conda/envs/envdecoil/lib/python3.8/site-packages/decoil-1.1.3a0-py3.8.egg/decoil/cli/sv-reconstruct.json
>         params: {'bam': 'map.bam', 'outputdir': 'decoil_example_s', 'reference_genome': 'reference.fa', 'annotation_gtf': 'anno.gtf', 'name': 'example_ecDNA', 'threads': 4, 'svcaller': 'sniffles', 'workflow': 'sv-reconstruct', 'container': False, 'decoil': '1.1.3-alpha'}
>         target: all
> --------
> Building DAG of jobs...
> Using shell: /bin/bash
> Provided cores: 1 (use --cores to define parallelism)
> Rules claiming more threads will be scaled down.
> Job stats:
> job          count
> ---------  -------
> all              1
> coverage         1
> decoil           1
> survivor         1
> svcalling        1
> total            5
> 
> Select jobs to execute...
> 
> 
> rule svcalling:
>     input: map.bam
>     output: decoil_example_s/sv.sniffles.vcf
>     log: decoil_example_s/logs/logs_sniffles
>     jobid: 1
>     reason: Forced execution
>     wildcards: dirname=decoil_example_s
>     resources: tmpdir=/junk/tmp//Etrz
> 
> 
>             sniffles -t 4 -m map.bam             -v decoil_example_s/sv.sniffles.vcf --min_homo_af 0.7             --min_het_af 0.1 --min_length 50             --cluster --genotype --min_support 4 --report-seq &> decoil_example_s/logs/logs_sniffles
> 
> Finished job 1.
> 1 of 5 steps (20%) done
> Select jobs to execute...
> 
> 
> rule survivor:
>     input: decoil_example_s/sv.sniffles.vcf
>     output: decoil_example_s/sv.sniffles.bedpe
>     log: decoil_example_s/logs/logs_survivor
>     jobid: 2
>     reason: Missing output files: decoil_example_s/sv.sniffles.bedpe; Input files updated by another job: decoil_example_s/sv.sniffles.vcf
>     wildcards: dirname=decoil_example_s
>     resources: tmpdir=/junk/tmp//Etrz
> 
> 
>         SURVIVOR vcftobed decoil_example_s/sv.sniffles.vcf -1 -1 decoil_example_s/sv.sniffles.bedpe &> decoil_example_s/logs/logs_survivor
>         
> 
> Finished job 2.
> 2 of 5 steps (40%) done
> Select jobs to execute...
> 
> 
> rule coverage:
>     input: map.bam, map.bam.bai
>     output: decoil_example_s/coverage.bw
>     log: decoil_example_s/logs/logs_cov
>     jobid: 3
>     reason: Forced execution
>     wildcards: dirname=decoil_example_s
>     resources: tmpdir=/junk/tmp//Etrz
> 
> 
>         bamCoverage --bam map.bam -o decoil_example_s/coverage.bw --binSize 50 -p 4 &> decoil_example_s/logs/logs_cov
>         
> 
> Finished job 3.
> 3 of 5 steps (60%) done
> Select jobs to execute...
> 
> 
> rule decoil:
>     input: decoil_example_s/sv.sniffles.vcf, decoil_example_s/coverage.bw, map.bam, map.bam.bai
>     output: decoil_example_s/summary.txt, decoil_example_s/reconstruct.bed, decoil_example_s/reconstruct.links.txt, decoil_example_s/reconstruct.fasta, decoil_example_s/reconstruct.ecDNA.bed, decoil_example_s/reconstruct.links.ecDNA.txt, decoil_example_s/reconstruct.ecDNA.fasta, decoil_example_s/reconstruct.ecDNA.filtered.bed, decoil_example_s/reconstruct.links.ecDNA.filtered.txt, decoil_example_s/reconstruct.ecDNA.filtered.fasta
>     log: decoil_example_s/logs/logs_decoil
>     jobid: 4
>     reason: Missing output files: decoil_example_s/reconstruct.links.txt, decoil_example_s/reconstruct.bed, decoil_example_s/reconstruct.links.ecDNA.filtered.txt, decoil_example_s/reconstruct.links.ecDNA.txt, decoil_example_s/summary.txt, decoil_example_s/reconstruct.ecDNA.bed, decoil_example_s/reconstruct.fasta, decoil_example_s/reconstruct.ecDNA.filtered.bed, decoil_example_s/reconstruct.ecDNA.filtered.fasta, decoil_example_s/reconstruct.ecDNA.fasta; Input files updated by another job: decoil_example_s/sv.sniffles.vcf, decoil_example_s/coverage.bw
>     wildcards: dirname=decoil_example_s
>     resources: tmpdir=/junk/tmp//Etrz
> 
> Building DAG of jobs...
> Using shell: /bin/bash
> Provided cores: 1 (use --cores to define parallelism)
> Rules claiming more threads will be scaled down.
> Select jobs to execute...
> [urlOpen] Couldn't open decoil_example_s/coverage.bw for reading
> [urlOpen] Couldn't open decoil_example_s/coverage.bw for reading
> [pyBwOpen] bw is NULL!
> [Sun Sep 29 16:55:31 2024]
> Error in rule decoil:
>     jobid: 0
>     input: decoil_example_s/sv.sniffles.vcf, decoil_example_s/coverage.bw, map.bam, map.bam.bai
>     output: decoil_example_s/summary.txt, decoil_example_s/reconstruct.bed, decoil_example_s/reconstruct.links.txt, decoil_example_s/reconstruct.fasta, decoil_example_s/reconstruct.ecDNA.bed, decoil_example_s/reconstruct.links.ecDNA.txt, decoil_example_s/reconstruct.ecDNA.fasta, decoil_example_s/reconstruct.ecDNA.filtered.bed, decoil_example_s/reconstruct.links.ecDNA.filtered.txt, decoil_example_s/reconstruct.ecDNA.filtered.fasta
>     log: decoil_example_s/logs/logs_decoil (check log file(s) for error details)
> 
> RuleException:
> RuntimeError in file /ngs/conda/envs/envdecoil/lib/python3.8/site-packages/decoil-1.1.3a0-py3.8.egg/decoil/cli/rules/decoil.smk, line 21:
> Received an error during file opening!
>   File "/ngs/conda/envs/envdecoil/lib/python3.8/site-packages/decoil-1.1.3a0-py3.8.egg/decoil/cli/rules/decoil.smk", line 21, in __rule_decoil
>   File "/ngs/conda/envs/envdecoil/lib/python3.8/site-packages/decoil-1.1.3a0-py3.8.egg/decoil/main.py", line 174, in run_reconstruction
>   File "/ngs/conda/envs/envdecoil/lib/python3.8/site-packages/decoil-1.1.3a0-py3.8.egg/decoil/output/metrics.py", line 106, in set_wgs
>   File "/ngs/conda/envs/envdecoil/lib/python3.8/site-packages/decoil-1.1.3a0-py3.8.egg/decoil/output/metrics.py", line 80, in compute_meancov
>   File "/ngs/conda/envs/envdecoil/lib/python3.8/concurrent/futures/thread.py", line 57, in run
> Shutting down, this might take some time.
> Exiting because a job execution failed. Look above for error message
> Shutting down, this might take some time.
> Exiting because a job execution failed. Look above for error message
> Complete log: .snakemake/log/2024-09-29T165353.181246.snakemake.log
> -------
> Status: Failed
> User time (seconds): 99.22
> #######
> 
> Traceback (most recent call last):
>   File "/ngs/conda/envs/envdecoil/lib/python3.8/site-packages/decoil-1.1.3a0-py3.8.egg/decoil/command.py", line 170, in entry_point
>     raise Exception("Snakemake failed")
> Exception: Snakemake failed
> ```

In your example you give as input `map.bam`. Since you use the installation from source where do you have the `map.bam` stored on your computer? 

I provided you https://github.com/madagiurgiu25/decoil-pre/issues/18#issuecomment-2380647075 (see one comment above) how you can download step by step and example and test the example using the installation from source. Did it worked for you?

**Comment by madagiurgiu25** [comment]
> Dear @madagiurgiu25, I would also like to ask about the steps taken to generate the example ecdna1/map.bam file. I noticed in the header that ngmlr is used for the aligments but I am curious to know if any additional steps were done as mark duplicates or generate consensus reads ( I have seen consensus reads in IGV when loading the example file). If so, could you indicate what programs were used for these steps ?.
> 
> I would also like to point out that when specifying the name using the --name option, the output files are default names (reconstruct....) instead of the specified name.

Dear @MJoseMo,

Decoil is developed for long-reads. Marking duplicates is typically a preprocessing step for short-reads. Which tool would you use for marking duplicates with long-read? Can you elaborate on what you refer as consensus reads? I think in IGV there is a option to visualize reads ("Show Consensus").

**Comment by madagiurgiu25** [comment]
Dear @MJoseMo,

I will close this ticket due to innactivity. But would like to point out that you can now install decoil via pip -> https://github.com/madagiurgiu25/decoil-pre/tree/main?tab=readme-ov-file#getting-started-using-conda-and-pip
