### ISSUE TITLE
Use singularity to run Decoil

### ISSUE THREAD

**Issue by madagiurgiu25** [madagiurgiu25/decoil-pre#2]
Run Decoil container using singularity.

**Comment by eesiribloom** [comment]
I managed to run decoil using singularity 
`singularity pull docker://madagiurgiu25/decoil:1.1.1-slim-test `

**Comment by thomasjay3** [comment]
Hi, I was wondering if there was a follow-up to this. I tried using singularity to run decoil, but I've been running into some issues. Is this currently supported? Happy to share the errors I'm running into. Thanks so much!

**Comment by madagiurgiu25** [comment]
Dear @thomasjay3,

I have updated now the documentation and suggested how you can run with singularity. Let me know if it worked for you. 
Thank you.
