### ISSUE TITLE
parameters

### ISSUE THREAD

**Issue by eesiribloom** [madagiurgiu25/decoil-pre#6]
I wasn't completely clear about all the parameters in the readme:
--sv-caller and --dry-run were not accepted
also, --dry-run (-n) and --name (-n) have the same input which wouldn't work?

**Comment by madagiurgiu25** [comment]
Dear @eesiribloom,

`--sv-caller` is currently deactivate and unvailable for this version.  By default Decoil uses internally `sniffles` to call variants. The method will be fully functional after the paper is published.

**Comment by madagiurgiu25** [comment]
Hi @eesiribloom,

I will close the issue due to inactivity. Please feel free to reopen if you have further questions.

Best,
Madalina
