### ISSUE TITLE
visualising the output of decoil

### ISSUE THREAD

**Issue by eesiribloom** [madagiurgiu25/decoil-pre#7]
If I have this output from decoil, which files can I use to visualise any potential ecDNA. The manuscript mentions using gGnome
clean.vcf
config.json
coverage.bw
fragments_clean_1.bed
fragments_clean_2.bed
fragments_clean_3.bed
fragments_initial.bed
graph.gpickle
logs
metrics_frag_cov_distribution.png
metrics_frag_len_cov_correlation.png
metrics_frag_len_distribution.png
reconstruct.bed
reconstruct.bed_debug
reconstruct.ecDNA.bed
reconstruct.json
reconstruct.links.txt_debug
sv.sniffles.bedpe
sv.sniffles.vcf

**Comment by madagiurgiu25** [comment]
Dear @eesiribloom,

I have created a separate repository for the visualization -> https://github.com/madagiurgiu25/decoil-viz

You would need the following files output by Decoil:

- coverage.bw
- reconstruct.ecDNA.filtered.bed
- reconstruct.links.ecDNA.filtered.txt
- summary.txt

**Comment by eesiribloom** [comment]
Okay thanks, for some reason these were not produced except coverage.bw (as mentioned in this [issue](https://github.com/madagiurgiu25/decoil-pre/issues/8)

**Comment by madagiurgiu25** [comment]
@eesiribloom, can I close this issue? Let me know if you have other questions.
Best,
Madalina
