### ISSUE TITLE
Hope a command only for Decoil Reconstruction

### ISSUE THREAD

**Issue by zhober** [madagiurgiu25/decoil-pre#9]
The current version of Decoil supports three tasks: SV calling using Sniffles1, bigWig track generation using bamCoverage and Decoil reconstruction. I hope to introduce a new command specifically for the third step or divide these three steps. This way, I can directly perform the third step when the files from the first two steps are available, making parameter testing more convenient.
Additionally, I notice the use of NanoFilt to filter Nanopore data in your pre-print. Is this step necessary?

**Comment by madagiurgiu25** [comment]
Thank you for your remark. Yes, Decoil contains the pre-processing steps, i.e. SV calling and bigWig track generation, both files required by the method. The current version focus primarily on usability over flexibility.  

NanoFilt it is not required for Decoil.

I will keep you updated when a reconstruction-only will be available.

**Comment by zhober** [comment]
Okay, thank you for your explanation!
